// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AlterStatement ALTER TABLE 실행 시 반환값.
 */
export class AlterStatement {
    /**
     * Creates a new AlterStatement instance.
     * @param {Partial<AlterStatement>} [$$source = {}] - The source object to create the AlterStatement.
     */
    constructor($$source = {}) {
        if (!("sql" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }
        if (!("preview" in $$source)) {
            /**
             * 사람이 읽기 쉬운 변경 요약
             * @member
             * @type {string}
             */
            this["preview"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AlterStatement instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AlterStatement}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AlterStatement(/** @type {Partial<AlterStatement>} */($$parsedSource));
    }
}

/**
 * CheckConstraintDef CHECK 제약 정의.
 */
export class CheckConstraintDef {
    /**
     * Creates a new CheckConstraintDef instance.
     * @param {Partial<CheckConstraintDef>} [$$source = {}] - The source object to create the CheckConstraintDef.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("expression" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expression"] = "";
        }
        if (!("enforced" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["enforced"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new CheckConstraintDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {CheckConstraintDef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new CheckConstraintDef(/** @type {Partial<CheckConstraintDef>} */($$parsedSource));
    }
}

/**
 * ColumnDef 테이블 컬럼 정의.
 */
export class ColumnDef {
    /**
     * Creates a new ColumnDef instance.
     * @param {Partial<ColumnDef>} [$$source = {}] - The source object to create the ColumnDef.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("dataType" in $$source)) {
            /**
             * int, varchar, text, ...
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("length" in $$source)) {
            /**
             * "255", "10,2" (DECIMAL)
             * @member
             * @type {string}
             */
            this["length"] = "";
        }
        if (!("notNull" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["notNull"] = false;
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default"] = "";
        }
        if (!("autoInc" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["autoInc"] = false;
        }
        if (!("primaryKey" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["primaryKey"] = false;
        }
        if (!("unique" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unique"] = false;
        }
        if (!("unsigned" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unsigned"] = false;
        }
        if (!("zeroFill" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["zeroFill"] = false;
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("ordinalPos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ordinalPos"] = 0;
        }
        if (!("collation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collation"] = "";
        }
        if (!("onUpdate" in $$source)) {
            /**
             * CURRENT_TIMESTAMP 등
             * @member
             * @type {string}
             */
            this["onUpdate"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * OriginalName 은 Phase 16 디자이너에서 rename 감지용으로 사용된다.
             * 빈 문자열이면 신규 컬럼으로 간주한다.
             * @member
             * @type {string | undefined}
             */
            this["originalName"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnDef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnDef(/** @type {Partial<ColumnDef>} */($$parsedSource));
    }
}

/**
 * ColumnInfo 컬럼 상세 정보.
 */
export class ColumnInfo {
    /**
     * Creates a new ColumnInfo instance.
     * @param {Partial<ColumnInfo>} [$$source = {}] - The source object to create the ColumnInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("ordinalPos" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["ordinalPos"] = 0;
        }
        if (!("default" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["default"] = "";
        }
        if (!("nullable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nullable"] = false;
        }
        if (!("dataType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["dataType"] = "";
        }
        if (!("columnType" in $$source)) {
            /**
             * 예: varchar(255)
             * @member
             * @type {string}
             */
            this["columnType"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * PRI, UNI, MUL
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("extra" in $$source)) {
            /**
             * auto_increment 등
             * @member
             * @type {string}
             */
            this["extra"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnInfo(/** @type {Partial<ColumnInfo>} */($$parsedSource));
    }
}

/**
 * ExplainRow EXPLAIN 결과 한 행.
 */
export class ExplainRow {
    /**
     * Creates a new ExplainRow instance.
     * @param {Partial<ExplainRow>} [$$source = {}] - The source object to create the ExplainRow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("selectType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["selectType"] = "";
        }
        if (!("table" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table"] = "";
        }
        if (!("partitions" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["partitions"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("possibleKeys" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["possibleKeys"] = "";
        }
        if (!("key" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["key"] = "";
        }
        if (!("keyLen" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["keyLen"] = "";
        }
        if (!("ref" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["ref"] = "";
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }
        if (!("filtered" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["filtered"] = 0;
        }
        if (!("extra" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["extra"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ExplainRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ExplainRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ExplainRow(/** @type {Partial<ExplainRow>} */($$parsedSource));
    }
}

/**
 * FKInfo information_schema에서 조회한 실제 외래키 정보.
 */
export class FKInfo {
    /**
     * Creates a new FKInfo instance.
     * @param {Partial<FKInfo>} [$$source = {}] - The source object to create the FKInfo.
     */
    constructor($$source = {}) {
        if (!("tableName" in $$source)) {
            /**
             * 자식 테이블 (FK를 가진 쪽)
             * @member
             * @type {string}
             */
            this["tableName"] = "";
        }
        if (!("columnName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["columnName"] = "";
        }
        if (!("refTableName" in $$source)) {
            /**
             * 부모 테이블 (참조 대상)
             * @member
             * @type {string}
             */
            this["refTableName"] = "";
        }
        if (!("refColumnName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refColumnName"] = "";
        }
        if (!("constraintName" in $$source)) {
            /**
             * 제약 조건 이름
             * @member
             * @type {string}
             */
            this["constraintName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new FKInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {FKInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new FKInfo(/** @type {Partial<FKInfo>} */($$parsedSource));
    }
}

/**
 * ForeignKeyDef 외래 키 정의.
 */
export class ForeignKeyDef {
    /**
     * Creates a new ForeignKeyDef instance.
     * @param {Partial<ForeignKeyDef>} [$$source = {}] - The source object to create the ForeignKeyDef.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("column" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("refTable" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refTable"] = "";
        }
        if (!("refColumn" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["refColumn"] = "";
        }
        if (!("onDelete" in $$source)) {
            /**
             * CASCADE | SET NULL | RESTRICT | NO ACTION
             * @member
             * @type {string}
             */
            this["onDelete"] = "";
        }
        if (!("onUpdate" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["onUpdate"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ForeignKeyDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ForeignKeyDef}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ForeignKeyDef(/** @type {Partial<ForeignKeyDef>} */($$parsedSource));
    }
}

/**
 * IndexDef 인덱스 정의.
 */
export class IndexDef {
    /**
     * Creates a new IndexDef instance.
     * @param {Partial<IndexDef>} [$$source = {}] - The source object to create the IndexDef.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["columns"] = [];
        }
        if (!("columnDirections" in $$source)) {
            /**
             * 각 컬럼의 정렬 방향: "ASC" | "DESC"
             * @member
             * @type {string[]}
             */
            this["columnDirections"] = [];
        }
        if (!("unique" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unique"] = false;
        }
        if (!("fullText" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["fullText"] = false;
        }
        if (!("indexType" in $$source)) {
            /**
             * BTREE | HASH
             * @member
             * @type {string}
             */
            this["indexType"] = "";
        }
        if (!("isPrimary" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isPrimary"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexDef instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IndexDef}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType0;
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField1_0($$parsedSource["columns"]);
        }
        if ("columnDirections" in $$parsedSource) {
            $$parsedSource["columnDirections"] = $$createField2_0($$parsedSource["columnDirections"]);
        }
        return new IndexDef(/** @type {Partial<IndexDef>} */($$parsedSource));
    }
}

/**
 * IndexInfo 인덱스 정보.
 */
export class IndexInfo {
    /**
     * Creates a new IndexInfo instance.
     * @param {Partial<IndexInfo>} [$$source = {}] - The source object to create the IndexInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["columns"] = "";
        }
        if (!("unique" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["unique"] = false;
        }
        if (!("indexType" in $$source)) {
            /**
             * BTREE, HASH, FULLTEXT
             * @member
             * @type {string}
             */
            this["indexType"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new IndexInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {IndexInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new IndexInfo(/** @type {Partial<IndexInfo>} */($$parsedSource));
    }
}

/**
 * ObjectInfo SP/Function/Trigger/Event 기본 정보.
 */
export class ObjectInfo {
    /**
     * Creates a new ObjectInfo instance.
     * @param {Partial<ObjectInfo>} [$$source = {}] - The source object to create the ObjectInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("objType" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["objType"] = "";
        }
        if (!("definer" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["definer"] = "";
        }
        if (!("created" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["created"] = "";
        }
        if (!("modified" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["modified"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ObjectInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ObjectInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ObjectInfo(/** @type {Partial<ObjectInfo>} */($$parsedSource));
    }
}

/**
 * PartitionInfo information_schema.PARTITIONS 조회 결과.
 */
export class PartitionInfo {
    /**
     * Creates a new PartitionInfo instance.
     * @param {Partial<PartitionInfo>} [$$source = {}] - The source object to create the PartitionInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("method" in $$source)) {
            /**
             * RANGE | LIST | HASH | KEY ...
             * @member
             * @type {string}
             */
            this["method"] = "";
        }
        if (!("expression" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["expression"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("tableRows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["tableRows"] = 0;
        }
        if (!("dataLength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dataLength"] = 0;
        }
        if (!("indexLength" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["indexLength"] = 0;
        }
        if (!("subpartitionName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["subpartitionName"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new PartitionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {PartitionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new PartitionInfo(/** @type {Partial<PartitionInfo>} */($$parsedSource));
    }
}

/**
 * ProfileRow SHOW PROFILE 결과 한 행.
 */
export class ProfileRow {
    /**
     * Creates a new ProfileRow instance.
     * @param {Partial<ProfileRow>} [$$source = {}] - The source object to create the ProfileRow.
     */
    constructor($$source = {}) {
        if (!("status" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["status"] = "";
        }
        if (!("duration" in $$source)) {
            /**
             * seconds
             * @member
             * @type {number}
             */
            this["duration"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProfileRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProfileRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProfileRow(/** @type {Partial<ProfileRow>} */($$parsedSource));
    }
}

/**
 * TableDefinition 전체 테이블 구조.
 */
export class TableDefinition {
    /**
     * Creates a new TableDefinition instance.
     * @param {Partial<TableDefinition>} [$$source = {}] - The source object to create the TableDefinition.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("engine" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["engine"] = "";
        }
        if (!("charset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["charset"] = "";
        }
        if (!("collation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collation"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {ColumnDef[]}
             */
            this["columns"] = [];
        }
        if (!("indexes" in $$source)) {
            /**
             * @member
             * @type {IndexDef[]}
             */
            this["indexes"] = [];
        }
        if (!("foreignKeys" in $$source)) {
            /**
             * @member
             * @type {ForeignKeyDef[]}
             */
            this["foreignKeys"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableDefinition instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableDefinition}
     */
    static createFrom($$source = {}) {
        const $$createField5_0 = $$createType2;
        const $$createField6_0 = $$createType4;
        const $$createField7_0 = $$createType6;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField5_0($$parsedSource["columns"]);
        }
        if ("indexes" in $$parsedSource) {
            $$parsedSource["indexes"] = $$createField6_0($$parsedSource["indexes"]);
        }
        if ("foreignKeys" in $$parsedSource) {
            $$parsedSource["foreignKeys"] = $$createField7_0($$parsedSource["foreignKeys"]);
        }
        return new TableDefinition(/** @type {Partial<TableDefinition>} */($$parsedSource));
    }
}

/**
 * TableInfo 테이블/뷰 기본 정보.
 */
export class TableInfo {
    /**
     * Creates a new TableInfo instance.
     * @param {Partial<TableInfo>} [$$source = {}] - The source object to create the TableInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * "BASE TABLE" | "VIEW"
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("engine" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["engine"] = "";
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["rows"] = 0;
        }
        if (!("sizeBytes" in $$source)) {
            /**
             * data_length + index_length
             * @member
             * @type {number}
             */
            this["sizeBytes"] = 0;
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TableInfo(/** @type {Partial<TableInfo>} */($$parsedSource));
    }
}

/**
 * TableMeta Phase 16 디자이너용 전체 메타데이터. 상단 탭과 하단 그리드에 필요한 모든 정보를 포함한다.
 */
export class TableMeta {
    /**
     * Creates a new TableMeta instance.
     * @param {Partial<TableMeta>} [$$source = {}] - The source object to create the TableMeta.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * 기본 정보
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("comment" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["comment"] = "";
        }
        if (!("engine" in $$source)) {
            /**
             * 옵션
             * @member
             * @type {string}
             */
            this["engine"] = "";
        }
        if (!("charset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["charset"] = "";
        }
        if (!("collation" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["collation"] = "";
        }
        if (!("autoIncrement" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["autoIncrement"] = 0;
        }
        if (!("rowFormat" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["rowFormat"] = "";
        }
        if (!("columns" in $$source)) {
            /**
             * 컬럼 및 제약
             * @member
             * @type {ColumnDef[]}
             */
            this["columns"] = [];
        }
        if (!("indexes" in $$source)) {
            /**
             * @member
             * @type {IndexDef[]}
             */
            this["indexes"] = [];
        }
        if (!("foreignKeys" in $$source)) {
            /**
             * @member
             * @type {ForeignKeyDef[]}
             */
            this["foreignKeys"] = [];
        }
        if (!("checkConstraints" in $$source)) {
            /**
             * @member
             * @type {CheckConstraintDef[]}
             */
            this["checkConstraints"] = [];
        }
        if (!("partitions" in $$source)) {
            /**
             * @member
             * @type {PartitionInfo[]}
             */
            this["partitions"] = [];
        }
        if (!("createStmt" in $$source)) {
            /**
             * SHOW CREATE TABLE 원본
             * @member
             * @type {string}
             */
            this["createStmt"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableMeta}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType2;
        const $$createField8_0 = $$createType4;
        const $$createField9_0 = $$createType6;
        const $$createField10_0 = $$createType8;
        const $$createField11_0 = $$createType10;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField7_0($$parsedSource["columns"]);
        }
        if ("indexes" in $$parsedSource) {
            $$parsedSource["indexes"] = $$createField8_0($$parsedSource["indexes"]);
        }
        if ("foreignKeys" in $$parsedSource) {
            $$parsedSource["foreignKeys"] = $$createField9_0($$parsedSource["foreignKeys"]);
        }
        if ("checkConstraints" in $$parsedSource) {
            $$parsedSource["checkConstraints"] = $$createField10_0($$parsedSource["checkConstraints"]);
        }
        if ("partitions" in $$parsedSource) {
            $$parsedSource["partitions"] = $$createField11_0($$parsedSource["partitions"]);
        }
        return new TableMeta(/** @type {Partial<TableMeta>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = ColumnDef.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = IndexDef.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = ForeignKeyDef.createFrom;
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = CheckConstraintDef.createFrom;
const $$createType8 = $Create.Array($$createType7);
const $$createType9 = PartitionInfo.createFrom;
const $$createType10 = $Create.Array($$createType9);
