// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * Snippet 즐겨찾기 항목.
 */
export class Snippet {
    /**
     * Creates a new Snippet instance.
     * @param {Partial<Snippet>} [$$source = {}] - The source object to create the Snippet.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("sql" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }
        if (!("category" in $$source)) {
            /**
             * 사용자 정의 카테고리 (예: "분석", "운영")
             * @member
             * @type {string}
             */
            this["category"] = "";
        }
        if (!("tags" in $$source)) {
            /**
             * @member
             * @type {string[]}
             */
            this["tags"] = [];
        }
        if (!("createdAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["createdAt"] = null;
        }
        if (!("updatedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["updatedAt"] = null;
        }
        if (!("useCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["useCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new Snippet instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {Snippet}
     */
    static createFrom($$source = {}) {
        const $$createField4_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tags" in $$parsedSource) {
            $$parsedSource["tags"] = $$createField4_0($$parsedSource["tags"]);
        }
        return new Snippet(/** @type {Partial<Snippet>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
