// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ColumnMeta 결과 컬럼 메타데이터.
 */
export class ColumnMeta {
    /**
     * Creates a new ColumnMeta instance.
     * @param {Partial<ColumnMeta>} [$$source = {}] - The source object to create the ColumnMeta.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("type" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["type"] = "";
        }
        if (!("nullable" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["nullable"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnMeta instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnMeta}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnMeta(/** @type {Partial<ColumnMeta>} */($$parsedSource));
    }
}

/**
 * ColumnValue InsertRow 파라미터용 컬럼·값 쌍.
 */
export class ColumnValue {
    /**
     * Creates a new ColumnValue instance.
     * @param {Partial<ColumnValue>} [$$source = {}] - The source object to create the ColumnValue.
     */
    constructor($$source = {}) {
        if (!("column" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }
        if (!("setNull" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["setNull"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ColumnValue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ColumnValue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ColumnValue(/** @type {Partial<ColumnValue>} */($$parsedSource));
    }
}

/**
 * ImportResult CSV 임포트 결과.
 */
export class ImportResult {
    /**
     * Creates a new ImportResult instance.
     * @param {Partial<ImportResult>} [$$source = {}] - The source object to create the ImportResult.
     */
    constructor($$source = {}) {
        if (!("inserted" in $$source)) {
            /**
             * 삽입된 행 수
             * @member
             * @type {number}
             */
            this["inserted"] = 0;
        }
        if (!("skipped" in $$source)) {
            /**
             * 건너뛴 행 수 (열 수 불일치 등)
             * @member
             * @type {number}
             */
            this["skipped"] = 0;
        }
        if (!("errors" in $$source)) {
            /**
             * 첫 번째 오류 메시지 (없으면 빈 문자열)
             * @member
             * @type {string}
             */
            this["errors"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ImportResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ImportResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ImportResult(/** @type {Partial<ImportResult>} */($$parsedSource));
    }
}

/**
 * MultiExecResult ExecuteMultiQuery 결과.
 * 중간 실패 시에도 부분 결과를 함께 반환하며, 에러 정보를 구조체에 내장한다.
 * Wails 바인딩이 항상 성공(rejection 없음)하도록 설계되어 있다.
 */
export class MultiExecResult {
    /**
     * Creates a new MultiExecResult instance.
     * @param {Partial<MultiExecResult>} [$$source = {}] - The source object to create the MultiExecResult.
     */
    constructor($$source = {}) {
        if (!("results" in $$source)) {
            /**
             * 성공한 쿼리 결과 목록
             * @member
             * @type {(QueryResult | null)[]}
             */
            this["results"] = [];
        }
        if (!("failedIndex" in $$source)) {
            /**
             * 실패한 statement 0-기반 인덱스 (-1 = 전부 성공)
             * @member
             * @type {number}
             */
            this["failedIndex"] = 0;
        }
        if (!("failedSQL" in $$source)) {
            /**
             * 실패한 SQL 문
             * @member
             * @type {string}
             */
            this["failedSQL"] = "";
        }
        if (!("error" in $$source)) {
            /**
             * 오류 메시지 (FailedIndex >= 0 일 때만 유효)
             * @member
             * @type {string}
             */
            this["error"] = "";
        }
        if (!("remainingSQL" in $$source)) {
            /**
             * 미실행 SQL (FailedIndex 다음 statement들)
             * @member
             * @type {string}
             */
            this["remainingSQL"] = "";
        }
        if (!("totalCount" in $$source)) {
            /**
             * 전체 statement 수
             * @member
             * @type {number}
             */
            this["totalCount"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new MultiExecResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {MultiExecResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("results" in $$parsedSource) {
            $$parsedSource["results"] = $$createField0_0($$parsedSource["results"]);
        }
        return new MultiExecResult(/** @type {Partial<MultiExecResult>} */($$parsedSource));
    }
}

/**
 * QueryResult SQL 실행 결과.
 */
export class QueryResult {
    /**
     * Creates a new QueryResult instance.
     * @param {Partial<QueryResult>} [$$source = {}] - The source object to create the QueryResult.
     */
    constructor($$source = {}) {
        if (!("columns" in $$source)) {
            /**
             * @member
             * @type {ColumnMeta[]}
             */
            this["columns"] = [];
        }
        if (!("rows" in $$source)) {
            /**
             * @member
             * @type {any[][]}
             */
            this["rows"] = [];
        }
        if (!("affected" in $$source)) {
            /**
             * INSERT/UPDATE/DELETE affected rows
             * @member
             * @type {number}
             */
            this["affected"] = 0;
        }
        if (!("lastId" in $$source)) {
            /**
             * INSERT last insert ID
             * @member
             * @type {number}
             */
            this["lastId"] = 0;
        }
        if (!("duration" in $$source)) {
            /**
             * 실행 시간 (nanoseconds)
             * @member
             * @type {time$0.Duration}
             */
            this["duration"] = time$0.Duration.$zero;
        }
        if (!("sql" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 인라인 편집 컨텍스트 (단일 테이블 SELECT)
             * @member
             * @type {TableEditContext | null | undefined}
             */
            this["editCtx"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * true = 결과 행 상한선 초과로 잘림
             * @member
             * @type {boolean | undefined}
             */
            this["truncated"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new QueryResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {QueryResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        const $$createField1_0 = $$createType6;
        const $$createField6_0 = $$createType8;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("columns" in $$parsedSource) {
            $$parsedSource["columns"] = $$createField0_0($$parsedSource["columns"]);
        }
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField1_0($$parsedSource["rows"]);
        }
        if ("editCtx" in $$parsedSource) {
            $$parsedSource["editCtx"] = $$createField6_0($$parsedSource["editCtx"]);
        }
        return new QueryResult(/** @type {Partial<QueryResult>} */($$parsedSource));
    }
}

/**
 * RowPKValue PK 컬럼과 그 값의 쌍 (UpdateRowValue 파라미터용).
 */
export class RowPKValue {
    /**
     * Creates a new RowPKValue instance.
     * @param {Partial<RowPKValue>} [$$source = {}] - The source object to create the RowPKValue.
     */
    constructor($$source = {}) {
        if (!("column" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * 모든 타입을 문자열로 직렬화
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new RowPKValue instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {RowPKValue}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new RowPKValue(/** @type {Partial<RowPKValue>} */($$parsedSource));
    }
}

/**
 * TableEditContext 인라인 편집을 위한 테이블 컨텍스트.
 * 단일 테이블 SELECT 쿼리에서 자동으로 채워진다.
 */
export class TableEditContext {
    /**
     * Creates a new TableEditContext instance.
     * @param {Partial<TableEditContext>} [$$source = {}] - The source object to create the TableEditContext.
     */
    constructor($$source = {}) {
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("table" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table"] = "";
        }
        if (!("pkColumns" in $$source)) {
            /**
             * PK 컬럼 이름 목록 (WHERE 절 빌드에 사용)
             * @member
             * @type {string[]}
             */
            this["pkColumns"] = [];
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TableEditContext instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TableEditContext}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType9;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("pkColumns" in $$parsedSource) {
            $$parsedSource["pkColumns"] = $$createField2_0($$parsedSource["pkColumns"]);
        }
        return new TableEditContext(/** @type {Partial<TableEditContext>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = QueryResult.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = ColumnMeta.createFrom;
const $$createType4 = $Create.Array($$createType3);
const $$createType5 = $Create.Array($Create.Any);
const $$createType6 = $Create.Array($$createType5);
const $$createType7 = TableEditContext.createFrom;
const $$createType8 = $Create.Nullable($$createType7);
const $$createType9 = $Create.Array($Create.Any);
