// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ConnectConfig MySQL 연결 설정.
 */
export class ConnectConfig {
    /**
     * Creates a new ConnectConfig instance.
     * @param {Partial<ConnectConfig>} [$$source = {}] - The source object to create the ConnectConfig.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 파일에 저장 시 항상 빈 문자열
             * @member
             * @type {string | undefined}
             */
            this["password"] = undefined;
        }
        if (!("database" in $$source)) {
            /**
             * 기본 접속 DB (Databases[0] 자동 동기)
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 즐겨찾기 DB 목록 (멀티셀렉)
             * @member
             * @type {string[] | undefined}
             */
            this["databases"] = undefined;
        }
        if (!("charset" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["charset"] = "";
        }
        if (!("tls" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["tls"] = false;
        }
        if (!("useSSH" in $$source)) {
            /**
             * SSH 터널 설정
             * @member
             * @type {boolean}
             */
            this["useSSH"] = false;
        }
        if (!("sshHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sshHost"] = "";
        }
        if (!("sshPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["sshPort"] = 0;
        }
        if (!("sshUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sshUser"] = "";
        }
        if (!("sshKeyPath" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sshKeyPath"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * SSH 패스워드 인증 (키 경로 없을 때 사용)
             * @member
             * @type {string | undefined}
             */
            this["sshPassword"] = undefined;
        }
        if (!("useProxy" in $$source)) {
            /**
             * 프록시 설정 (Phase 6-F: SOCKS5 | HTTP CONNECT)
             * @member
             * @type {boolean}
             */
            this["useProxy"] = false;
        }
        if (!("proxyType" in $$source)) {
            /**
             * "socks5" | "http"
             * @member
             * @type {string}
             */
            this["proxyType"] = "";
        }
        if (!("proxyHost" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyHost"] = "";
        }
        if (!("proxyPort" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["proxyPort"] = 0;
        }
        if (!("proxyUser" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["proxyUser"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 파일에 저장 시 항상 빈 문자열
             * @member
             * @type {string | undefined}
             */
            this["proxyPassword"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 세션 관리 메타데이터
             * 소속 그룹 ID ("" = 루트)
             * @member
             * @type {string | undefined}
             */
            this["groupId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 세션 색상 hex (e.g. "#4299e1")
             * @member
             * @type {string | undefined}
             */
            this["color"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 마지막 연결 시각
             * @member
             * @type {time$0.Time | undefined}
             */
            this["lastUsed"] = undefined;
        }
        if (!("sortOrder" in $$source)) {
            /**
             * 그룹 내 정렬 순서
             * @member
             * @type {number}
             */
            this["sortOrder"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectConfig instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectConfig}
     */
    static createFrom($$source = {}) {
        const $$createField7_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("databases" in $$parsedSource) {
            $$parsedSource["databases"] = $$createField7_0($$parsedSource["databases"]);
        }
        return new ConnectConfig(/** @type {Partial<ConnectConfig>} */($$parsedSource));
    }
}

/**
 * ConnectionInfo 활성 연결 상태 정보.
 * 
 * ID 는 휘발 runtime 식별자(`ConnectAsNewSession` 경로에선 매번 새 UUID).
 * CfgID 는 저장 연결(`connections.json`) 의 영구 ID — MCP allowlist·세션 복원 등 영구 식별이 필요한 곳에서 사용한다.
 * 두 값이 같을 수도(예: legacy `Connect()` 경로, cfg.ID 가 그대로 runtime ID 로 쓰임), 다를 수도 있다(ConnectAsNewSession).
 */
export class ConnectionInfo {
    /**
     * Creates a new ConnectionInfo instance.
     * @param {Partial<ConnectionInfo>} [$$source = {}] - The source object to create the ConnectionInfo.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * BugFix-DA: 저장 연결 ID (영구). 빈 문자열 = unsaved.
             * @member
             * @type {string | undefined}
             */
            this["cfgId"] = undefined;
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("port" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["port"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("connectedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["connectedAt"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ConnectionInfo(/** @type {Partial<ConnectionInfo>} */($$parsedSource));
    }
}

/**
 * KnownHostEntry known_hosts 파일의 개별 항목.
 */
export class KnownHostEntry {
    /**
     * Creates a new KnownHostEntry instance.
     * @param {Partial<KnownHostEntry>} [$$source = {}] - The source object to create the KnownHostEntry.
     */
    constructor($$source = {}) {
        if (!("line" in $$source)) {
            /**
             * 원본 텍스트 라인
             * @member
             * @type {string}
             */
            this["line"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * 호스트명/IP
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("keyType" in $$source)) {
            /**
             * 키 타입 (ssh-rsa, ecdsa-sha2-nistp256 등)
             * @member
             * @type {string}
             */
            this["keyType"] = "";
        }
        if (!("fingerprint" in $$source)) {
            /**
             * SHA256 핑거프린트
             * @member
             * @type {string}
             */
            this["fingerprint"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new KnownHostEntry instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {KnownHostEntry}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new KnownHostEntry(/** @type {Partial<KnownHostEntry>} */($$parsedSource));
    }
}

/**
 * SessionGroup 세션 그룹 (폴더).
 * 최대 2단계: 루트 그룹(ParentID="") → 하위 그룹(ParentID=상위ID).
 */
export class SessionGroup {
    /**
     * Creates a new SessionGroup instance.
     * @param {Partial<SessionGroup>} [$$source = {}] - The source object to create the SessionGroup.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (/** @type {any} */(false)) {
            /**
             * 그룹 색상 hex
             * @member
             * @type {string | undefined}
             */
            this["color"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * "" = 루트 레벨
             * @member
             * @type {string | undefined}
             */
            this["parentId"] = undefined;
        }
        if (!("order" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["order"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionGroup instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionGroup}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SessionGroup(/** @type {Partial<SessionGroup>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
