// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * DataDiffAction 데이터 차이 액션 타입.
 * @readonly
 * @enum {string}
 */
export const DataDiffAction = {
    /**
     * The Go zero value for the underlying type of the enum.
     */
    $zero: "",

    /**
     * 소스에만 있음 → 대상에 삽입
     */
    DataDiffInsert: "INSERT",

    /**
     * 양쪽 모두 있으나 값이 다름
     */
    DataDiffUpdate: "UPDATE",

    /**
     * 대상에만 있음 → 대상에서 삭제
     */
    DataDiffDelete: "DELETE",
};

/**
 * DataDiffRow 한 행의 데이터 차이.
 */
export class DataDiffRow {
    /**
     * Creates a new DataDiffRow instance.
     * @param {Partial<DataDiffRow>} [$$source = {}] - The source object to create the DataDiffRow.
     */
    constructor($$source = {}) {
        if (!("pk" in $$source)) {
            /**
             * PK 값 (복합 PK는 "|" 구분)
             * @member
             * @type {string}
             */
            this["pk"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * INSERT | UPDATE | DELETE
             * @member
             * @type {DataDiffAction}
             */
            this["action"] = DataDiffAction.$zero;
        }
        if (!("srcRow" in $$source)) {
            /**
             * 소스 행 (DELETE 시 nil)
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["srcRow"] = {};
        }
        if (!("dstRow" in $$source)) {
            /**
             * 대상 행 (INSERT 시 nil)
             * @member
             * @type {{ [_ in string]?: string }}
             */
            this["dstRow"] = {};
        }
        if (!("sql" in $$source)) {
            /**
             * 동기화 SQL
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataDiffRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DataDiffRow}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        const $$createField3_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("srcRow" in $$parsedSource) {
            $$parsedSource["srcRow"] = $$createField2_0($$parsedSource["srcRow"]);
        }
        if ("dstRow" in $$parsedSource) {
            $$parsedSource["dstRow"] = $$createField3_0($$parsedSource["dstRow"]);
        }
        return new DataDiffRow(/** @type {Partial<DataDiffRow>} */($$parsedSource));
    }
}

/**
 * DataSyncResult 데이터 비교 결과.
 */
export class DataSyncResult {
    /**
     * Creates a new DataSyncResult instance.
     * @param {Partial<DataSyncResult>} [$$source = {}] - The source object to create the DataSyncResult.
     */
    constructor($$source = {}) {
        if (!("table" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table"] = "";
        }
        if (!("srcCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["srcCount"] = 0;
        }
        if (!("dstCount" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["dstCount"] = 0;
        }
        if (!("diffs" in $$source)) {
            /**
             * @member
             * @type {DataDiffRow[]}
             */
            this["diffs"] = [];
        }
        if (!("syncSql" in $$source)) {
            /**
             * 전체 동기화 SQL (concat)
             * @member
             * @type {string}
             */
            this["syncSql"] = "";
        }
        if (!("analyzed" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["analyzed"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSyncResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DataSyncResult}
     */
    static createFrom($$source = {}) {
        const $$createField3_0 = $$createType2;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("diffs" in $$parsedSource) {
            $$parsedSource["diffs"] = $$createField3_0($$parsedSource["diffs"]);
        }
        return new DataSyncResult(/** @type {Partial<DataSyncResult>} */($$parsedSource));
    }
}

/**
 * SchemaDiffItem 두 스키마 간 차이 항목.
 */
export class SchemaDiffItem {
    /**
     * Creates a new SchemaDiffItem instance.
     * @param {Partial<SchemaDiffItem>} [$$source = {}] - The source object to create the SchemaDiffItem.
     */
    constructor($$source = {}) {
        if (!("objectType" in $$source)) {
            /**
             * "TABLE" | "COLUMN" | "INDEX"
             * @member
             * @type {string}
             */
            this["objectType"] = "";
        }
        if (!("objectName" in $$source)) {
            /**
             * 테이블명
             * @member
             * @type {string}
             */
            this["objectName"] = "";
        }
        if (!("subName" in $$source)) {
            /**
             * 컬럼/인덱스명 (해당 시)
             * @member
             * @type {string}
             */
            this["subName"] = "";
        }
        if (!("action" in $$source)) {
            /**
             * "ADD" | "DROP" | "MODIFY"
             * @member
             * @type {string}
             */
            this["action"] = "";
        }
        if (!("sourceDdl" in $$source)) {
            /**
             * 소스 정의
             * @member
             * @type {string}
             */
            this["sourceDdl"] = "";
        }
        if (!("targetDdl" in $$source)) {
            /**
             * 대상 정의 (없으면 "")
             * @member
             * @type {string}
             */
            this["targetDdl"] = "";
        }
        if (!("sql" in $$source)) {
            /**
             * 동기화 SQL
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaDiffItem instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchemaDiffItem}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new SchemaDiffItem(/** @type {Partial<SchemaDiffItem>} */($$parsedSource));
    }
}

/**
 * SchemaSyncResult 스키마 비교 결과.
 */
export class SchemaSyncResult {
    /**
     * Creates a new SchemaSyncResult instance.
     * @param {Partial<SchemaSyncResult>} [$$source = {}] - The source object to create the SchemaSyncResult.
     */
    constructor($$source = {}) {
        if (!("diffs" in $$source)) {
            /**
             * @member
             * @type {SchemaDiffItem[]}
             */
            this["diffs"] = [];
        }
        if (!("syncSql" in $$source)) {
            /**
             * 전체 동기화 SQL (concat)
             * @member
             * @type {string}
             */
            this["syncSql"] = "";
        }
        if (!("analyzed" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["analyzed"] = null;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SchemaSyncResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SchemaSyncResult}
     */
    static createFrom($$source = {}) {
        const $$createField0_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("diffs" in $$parsedSource) {
            $$parsedSource["diffs"] = $$createField0_0($$parsedSource["diffs"]);
        }
        return new SchemaSyncResult(/** @type {Partial<SchemaSyncResult>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Map($Create.Any, $Create.Any);
const $$createType1 = DataDiffRow.createFrom;
const $$createType2 = $Create.Array($$createType1);
const $$createType3 = SchemaDiffItem.createFrom;
const $$createType4 = $Create.Array($$createType3);
