// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as time$0 from "../../../time/models.js";

/**
 * ConnectionSessionState 연결별 독립 세션 상태 (Phase 14-A).
 * 각 연결마다 자신의 쿼리 탭, 활성 탭, 선택 DB를 가진다.
 */
export class ConnectionSessionState {
    /**
     * Creates a new ConnectionSessionState instance.
     * @param {Partial<ConnectionSessionState>} [$$source = {}] - The source object to create the ConnectionSessionState.
     */
    constructor($$source = {}) {
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["selectedDatabase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {TabState[] | undefined}
             */
            this["tabs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["activeTabId"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ConnectionSessionState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ConnectionSessionState}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField1_0($$parsedSource["tabs"]);
        }
        return new ConnectionSessionState(/** @type {Partial<ConnectionSessionState>} */($$parsedSource));
    }
}

/**
 * SessionState 앱 전체 세션 상태.
 * 
 * Phase 14-A: 연결별 상태는 PerConnection 맵에 저장된다.
 * BugFix-BK: PerConnection 키와 ActiveCfgIDs 가 모두 영구 cfgId 기반.
 * 휘발성 connID(매 연결마다 ConnectNew 가 새로 발급) 는 직렬화하지 않는다.
 * Tabs / ActiveTabID / SelectedDatabase / ActiveConnIDs 는 구버전 호환을 위한 deprecated 필드로,
 * Load() 시 PerConnection 으로 자동 마이그레이션된다.
 */
export class SessionState {
    /**
     * Creates a new SessionState instance.
     * @param {Partial<SessionState>} [$$source = {}] - The source object to create the SessionState.
     */
    constructor($$source = {}) {
        if (!("savedAt" in $$source)) {
            /**
             * @member
             * @type {time$0.Time}
             */
            this["savedAt"] = null;
        }
        if (/** @type {any} */(false)) {
            /**
             * BugFix-BK: 연결별 독립 세션 (key = cfgId — 저장된 연결 영구 ID).
             * 한 cfgId 를 두 탭으로 열어도 마지막 종료 시점 상태로 단일 항목 보존.
             * @member
             * @type {{ [_ in string]?: ConnectionSessionState } | undefined}
             */
            this["perConnection"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * BugFix-BK: 자동 재연결 대상 (cfgId 목록). 같은 cfgId 가 여러 번 등장하면 그 만큼 탭이 열림.
             * @member
             * @type {string[] | undefined}
             */
            this["activeCfgIds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * BugFix-BK: 마지막 활성 연결의 cfgId. 복원 후 첫 매칭 newConnId 를 selectedConnId 로 사용.
             * @member
             * @type {string | undefined}
             */
            this["selectedCfgId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ── Deprecated: 구버전 호환 (Phase 14 포맷) ──
             * Load 시 ActiveCfgIDs 가 비어있으면 ActiveConnIDs 를 그대로 폴백 시도하지만,
             * 휘발 UUID 라 GetConnectionWithCredential 이 실패할 수 있다(BugFix-BK 도입 이전 세션).
             * @member
             * @type {string[] | undefined}
             */
            this["activeConnIds"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["selectedConnId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * ── Deprecated: 구버전 호환 (Load 시 PerConnection 으로 자동 이관) ──
             * @member
             * @type {TabState[] | undefined}
             */
            this["tabs"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["activeTabId"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["selectedDatabase"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 사용 안 함 (Phase 14에서 복원 범위 외)
             * @member
             * @type {string[] | undefined}
             */
            this["schemaExpanded"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 사용 안 함 (Phase 14에서 복원 범위 외)
             * @member
             * @type {string[] | undefined}
             */
            this["openPanels"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new SessionState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {SessionState}
     */
    static createFrom($$source = {}) {
        const $$createField1_0 = $$createType3;
        const $$createField2_0 = $$createType4;
        const $$createField4_0 = $$createType4;
        const $$createField6_0 = $$createType1;
        const $$createField9_0 = $$createType4;
        const $$createField10_0 = $$createType4;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("perConnection" in $$parsedSource) {
            $$parsedSource["perConnection"] = $$createField1_0($$parsedSource["perConnection"]);
        }
        if ("activeCfgIds" in $$parsedSource) {
            $$parsedSource["activeCfgIds"] = $$createField2_0($$parsedSource["activeCfgIds"]);
        }
        if ("activeConnIds" in $$parsedSource) {
            $$parsedSource["activeConnIds"] = $$createField4_0($$parsedSource["activeConnIds"]);
        }
        if ("tabs" in $$parsedSource) {
            $$parsedSource["tabs"] = $$createField6_0($$parsedSource["tabs"]);
        }
        if ("schemaExpanded" in $$parsedSource) {
            $$parsedSource["schemaExpanded"] = $$createField9_0($$parsedSource["schemaExpanded"]);
        }
        if ("openPanels" in $$parsedSource) {
            $$parsedSource["openPanels"] = $$createField10_0($$parsedSource["openPanels"]);
        }
        return new SessionState(/** @type {Partial<SessionState>} */($$parsedSource));
    }
}

/**
 * TabState 탭 하나의 저장 상태.
 */
export class TabState {
    /**
     * Creates a new TabState instance.
     * @param {Partial<TabState>} [$$source = {}] - The source object to create the TabState.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["id"] = "";
        }
        if (!("title" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["title"] = "";
        }
        if (!("sql" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["sql"] = "";
        }
        if (!("connId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connId"] = "";
        }
        if (!("connName" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connName"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("isActive" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["isActive"] = false;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TabState instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TabState}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TabState(/** @type {Partial<TabState>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = TabState.createFrom;
const $$createType1 = $Create.Array($$createType0);
const $$createType2 = ConnectionSessionState.createFrom;
const $$createType3 = $Create.Map($Create.Any, $$createType2);
const $$createType4 = $Create.Array($Create.Any);
