// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

/**
 * App는 Wails v3 서비스 바인딩 레이어.
 * 프론트엔드에서 호출하는 모든 public 메서드가 여기에 정의된다.
 * @module
 */

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Call as $Call, CancellablePromise as $CancellablePromise, Create as $Create } from "@wailsio/runtime";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as application$0 from "../github.com/wailsapp/wails/v3/pkg/application/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as backup$0 from "./internal/backup/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as connection$0 from "./internal/connection/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as favorite$0 from "./internal/favorite/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as history$0 from "./internal/history/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as mcp$0 from "./internal/mcp/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as query$0 from "./internal/query/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as schema$0 from "./internal/schema/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as session$0 from "./internal/session/models.js";
// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as sync$0 from "./internal/sync/models.js";

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import * as $models from "./models.js";

/**
 * AddFavorite 새 즐겨찾기를 추가한다.
 * @param {favorite$0.Snippet} snippet
 * @returns {$CancellablePromise<void>}
 */
export function AddFavorite(snippet) {
    return $Call.ByID(2305501792, snippet);
}

/**
 * ApplySyncSQL 동기화 SQL을 대상 연결에 실행한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} sql
 * @returns {$CancellablePromise<void>}
 */
export function ApplySyncSQL(connID, database, sql) {
    return $Call.ByID(4231345792, connID, database, sql);
}

/**
 * BuildTableAlter Phase 16 디자이너 전용 — TableMeta 변경 diff를 ALTER SQL로 생성한다.
 * @param {string} database
 * @param {string} table
 * @param {schema$0.TableMeta | null} old
 * @param {schema$0.TableMeta | null} newMeta
 * @returns {$CancellablePromise<schema$0.AlterStatement | null>}
 */
export function BuildTableAlter(database, table, old, newMeta) {
    return $Call.ByID(3257511587, database, table, old, newMeta).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * CancelQuery 실행 중인 쿼리를 취소한다.
 * tabID: ExecuteMultiQuery 호출 시 전달한 tabID (cancelFuncs 키).
 * @param {string} tabID
 * @returns {$CancellablePromise<void>}
 */
export function CancelQuery(tabID) {
    return $Call.ByID(3431763441, tabID);
}

/**
 * ChangeUserPassword 기존 사용자의 비밀번호를 변경한다.
 * @param {string} connID
 * @param {string} user
 * @param {string} host
 * @param {string} newPassword
 * @returns {$CancellablePromise<void>}
 */
export function ChangeUserPassword(connID, user, host, newPassword) {
    return $Call.ByID(3110763167, connID, user, host, newPassword);
}

/**
 * CheckMCPPortAvailable 지정 포트가 즉시 listen 가능한지 빠르게 확인한다.
 * 활성화 토글 / 포트 변경 직전에 호출해 사용자에게 미리 경고하는 용도.
 * 
 * 주의: 우리 서버가 이미 그 포트에서 돌고 있어도 false 반환 — 호출자(프론트)는
 * GetMCPStatus 와 비교해 본인 서버인지 구분해야 한다.
 * @param {number} port
 * @returns {$CancellablePromise<boolean>}
 */
export function CheckMCPPortAvailable(port) {
    return $Call.ByID(4083062485, port);
}

/**
 * ClearHistory 히스토리 전체를 삭제한다.
 * @returns {$CancellablePromise<void>}
 */
export function ClearHistory() {
    return $Call.ByID(3429172794);
}

/**
 * ClearSession 세션 파일을 삭제한다.
 * @returns {$CancellablePromise<void>}
 */
export function ClearSession() {
    return $Call.ByID(1822206926);
}

/**
 * CompareSchemas 두 스키마를 비교해 diff 결과를 반환한다.
 * @param {string} srcConnID
 * @param {string} srcDB
 * @param {string} dstConnID
 * @param {string} dstDB
 * @returns {$CancellablePromise<sync$0.SchemaSyncResult | null>}
 */
export function CompareSchemas(srcConnID, srcDB, dstConnID, dstDB) {
    return $Call.ByID(2227447996, srcConnID, srcDB, dstConnID, dstDB).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType3($result);
    }));
}

/**
 * CompareTableData 소스와 대상 테이블의 데이터를 PK 기준으로 비교한다.
 * maxRows가 0이면 5000행으로 제한한다.
 * @param {string} srcConnID
 * @param {string} srcDB
 * @param {string} srcTable
 * @param {string} dstConnID
 * @param {string} dstDB
 * @param {string} dstTable
 * @param {number} maxRows
 * @returns {$CancellablePromise<sync$0.DataSyncResult | null>}
 */
export function CompareTableData(srcConnID, srcDB, srcTable, dstConnID, dstDB, dstTable, maxRows) {
    return $Call.ByID(2739908776, srcConnID, srcDB, srcTable, dstConnID, dstDB, dstTable, maxRows).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType5($result);
    }));
}

/**
 * Connect MySQL 서버에 연결하고 connID를 반환한다.
 * @param {connection$0.ConnectConfig} cfg
 * @returns {$CancellablePromise<string>}
 */
export function Connect(cfg) {
    return $Call.ByID(164877153, cfg);
}

/**
 * ConnectNew Connect 와 동일하지만 cfg.ID 와 무관하게 항상 새 runtime connID 를 발급한다.
 * 같은 저장된 연결을 여러 탭에서 동시에 열 때(BugFix-BA: 신규 연결 = 새 탭) 사용한다.
 * 
 * BugFix-DA: cfg.ID 를 클리어하지 않고 그대로 `ConnectAsNewSession` 에 넘긴다.
 * manager 가 cfg.ID 를 영구 cfgId 로 해석해 `info.CfgID` 에 보존 → MCP 의 active 마킹/
 * allowlist 매칭이 정상 동작한다. 키체인 비밀번호 복원은 manager.Connect 가 cfg.ID 로 처리.
 * @param {connection$0.ConnectConfig} cfg
 * @returns {$CancellablePromise<string>}
 */
export function ConnectNew(cfg) {
    return $Call.ByID(335045165, cfg);
}

/**
 * CopyTable 테이블 구조를 복사한다. withData=true 이면 데이터도 함께 복사한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} srcTable
 * @param {string} dstTable
 * @param {boolean} withData
 * @returns {$CancellablePromise<void>}
 */
export function CopyTable(connID, database, srcTable, dstTable, withData) {
    return $Call.ByID(2675317344, connID, database, srcTable, dstTable, withData);
}

/**
 * CreateDatabase 새 데이터베이스를 생성한다.
 * @param {string} connID
 * @param {string} database
 * @returns {$CancellablePromise<void>}
 */
export function CreateDatabase(connID, database) {
    return $Call.ByID(3436940056, connID, database);
}

/**
 * CreateUser 새 MySQL 사용자를 생성한다.
 * @param {string} connID
 * @param {string} user
 * @param {string} host
 * @param {string} password
 * @returns {$CancellablePromise<void>}
 */
export function CreateUser(connID, user, host, password) {
    return $Call.ByID(2169662290, connID, user, host, password);
}

/**
 * DeleteConnection 연결 설정을 삭제한다 (키체인 + MCP allowlist 포함).
 * MySQL / SSH / Proxy 세 키체인 엔트리 모두 제거하고, MCP allowlist 에 남은
 * 죽은 connID 도 정리한다 (Phase 43 보완).
 * 
 * MCP 정리는 best-effort: 실패해도 본 삭제 결과에 영향 X. 현재 실행 중인 서버의
 * in-memory 정책 스냅샷은 그대로 — 다음 Restart 시점에 디스크에서 새로 로드.
 * 살아있는 호출 흐름엔 영향 없음 (assertConnAllowedAndActive 가 어차피 거부).
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function DeleteConnection(connID) {
    return $Call.ByID(3428926502, connID);
}

/**
 * DeleteFavorite 즐겨찾기를 삭제한다.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteFavorite(id) {
    return $Call.ByID(224129662, id);
}

/**
 * DeleteHistoryEntry 특정 히스토리 항목을 삭제한다.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function DeleteHistoryEntry(id) {
    return $Call.ByID(3534299594, id);
}

/**
 * DeleteKnownHost ~/.orcasql/known_hosts에서 특정 라인을 삭제한다.
 * @param {string} line
 * @returns {$CancellablePromise<void>}
 */
export function DeleteKnownHost(line) {
    return $Call.ByID(3617919435, line);
}

/**
 * DeleteSessionGroup 그룹을 삭제한다. cascade=true이면 하위 세션도 함께 삭제한다.
 * @param {string} groupID
 * @param {boolean} cascade
 * @returns {$CancellablePromise<void>}
 */
export function DeleteSessionGroup(groupID, cascade) {
    return $Call.ByID(3923668153, groupID, cascade);
}

/**
 * Disconnect 연결을 해제한다.
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function Disconnect(connID) {
    return $Call.ByID(3864343059, connID);
}

/**
 * DropDatabase 데이터베이스를 삭제한다.
 * @param {string} connID
 * @param {string} database
 * @returns {$CancellablePromise<void>}
 */
export function DropDatabase(connID, database) {
    return $Call.ByID(1119946489, connID, database);
}

/**
 * DropUser MySQL 사용자를 삭제한다.
 * @param {string} connID
 * @param {string} user
 * @param {string} host
 * @returns {$CancellablePromise<void>}
 */
export function DropUser(connID, user, host) {
    return $Call.ByID(2733950119, connID, user, host);
}

/**
 * DumpDatabase 데이터베이스를 SQL 파일로 덤프하고 내용을 문자열로 반환한다.
 * 대용량 DB는 progress 이벤트(backup:progress)를 emit한다.
 * @param {backup$0.DumpOptions} opts
 * @returns {$CancellablePromise<string>}
 */
export function DumpDatabase(opts) {
    return $Call.ByID(4068331946, opts);
}

/**
 * ExecuteAlterTable ALTER TABLE SQL을 실행한다.
 * @param {string} connID
 * @param {string} sql
 * @returns {$CancellablePromise<void>}
 */
export function ExecuteAlterTable(connID, sql) {
    return $Call.ByID(1712718940, connID, sql);
}

/**
 * ExecuteMultiQuery 세미콜론으로 구분된 여러 SQL 문을 순차 실행하고 MultiExecResult를 반환한다.
 * tabID는 cancelFuncs 키로 사용되어 탭별 독립 취소를 지원한다.
 * 실패 시에도 Wails 바인딩에서 오류를 발생시키지 않는다 (부분 결과 + 오류가 구조체에 내장).
 * 프론트엔드에서 failedIndex >= 0 을 감지해 계속/중단 선택 대화를 표시한다.
 * @param {string} connID
 * @param {string} tabID
 * @param {string} connName
 * @param {string} database
 * @param {string} sql
 * @returns {$CancellablePromise<query$0.MultiExecResult | null>}
 */
export function ExecuteMultiQuery(connID, tabID, connName, database, sql) {
    return $Call.ByID(2140517715, connID, tabID, connName, database, sql).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType7($result);
    }));
}

/**
 * ExecuteQuery SQL을 실행하고 결과를 반환한다.
 * 실행 결과(성공/실패 모두)는 히스토리에 자동 저장된다.
 * @param {string} connID
 * @param {string} connName
 * @param {string} database
 * @param {string} sql
 * @returns {$CancellablePromise<query$0.QueryResult | null>}
 */
export function ExecuteQuery(connID, connName, database, sql) {
    return $Call.ByID(2868660388, connID, connName, database, sql).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType9($result);
    }));
}

/**
 * ExecuteQueryStream 대용량 쿼리를 청크 단위로 스트리밍 실행한다.
 * 결과는 "query:chunk" Wails 이벤트로 전달된다.
 * @param {string} connID
 * @param {string} sql
 * @returns {$CancellablePromise<void>}
 */
export function ExecuteQueryStream(connID, sql) {
    return $Call.ByID(503886492, connID, sql);
}

/**
 * ExportConnections 저장된 연결 설정을 JSON 문자열로 내보낸다 (비밀번호 제외, 그룹 포함).
 * @returns {$CancellablePromise<string>}
 */
export function ExportConnections() {
    return $Call.ByID(1210140840);
}

/**
 * ExportTableData 테이블 데이터를 지정 포맷(csv/json/sql)으로 내보낸다.
 * limit이 0이면 최대 10000행을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} table
 * @param {string} format
 * @param {number} limit
 * @returns {$CancellablePromise<string>}
 */
export function ExportTableData(connID, database, table, format, limit) {
    return $Call.ByID(2494962653, connID, database, table, format, limit);
}

/**
 * GenerateAlterSQL old → new 기준으로 ALTER TABLE SQL을 생성한다 (미리보기용).
 * @param {string} database
 * @param {string} table
 * @param {schema$0.TableDefinition | null} old
 * @param {schema$0.TableDefinition | null} $new
 * @returns {$CancellablePromise<schema$0.AlterStatement | null>}
 */
export function GenerateAlterSQL(database, table, old, $new) {
    return $Call.ByID(2125708910, database, table, old, $new).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GenerateCreateSQL 신규 테이블 디자이너 모드에서 def → CREATE TABLE SQL 을 생성한다.
 * @param {string} database
 * @param {schema$0.TableDefinition | null} def
 * @returns {$CancellablePromise<schema$0.AlterStatement | null>}
 */
export function GenerateCreateSQL(database, def) {
    return $Call.ByID(4057337658, database, def).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType1($result);
    }));
}

/**
 * GetAppInfo About 다이얼로그용 앱 정보를 반환한다.
 * @returns {$CancellablePromise<$models.AppInfo>}
 */
export function GetAppInfo() {
    return $Call.ByID(713661858).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType10($result);
    }));
}

/**
 * GetConnectionWithCredential 저장된 연결 1건을 ID 로 조회해 반환한다.
 * 세션 복원의 자동 재연결 흐름이 호출 — frontend 가 받은 cfg 를 그대로 Connect 에 넘기면
 * Connect 가 keychain 에서 비밀번호를 자동 복원한다 (평문은 JS 에 절대 노출 안 됨).
 * 
 * 미존재 ID 는 명시적 에러로 반환 — caller (App.tsx 자동 재연결) 가 try/catch 로 흡수.
 * @param {string} connID
 * @returns {$CancellablePromise<connection$0.ConnectConfig>}
 */
export function GetConnectionWithCredential(connID) {
    return $Call.ByID(1865150566, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType11($result);
    }));
}

/**
 * GetDatabaseOverview는 선택 DB 의 요약을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @returns {$CancellablePromise<$models.DatabaseOverview | null>}
 */
export function GetDatabaseOverview(connID, database) {
    return $Call.ByID(3293556921, connID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType13($result);
    }));
}

/**
 * GetDumpTableList 덤프 대상 테이블 목록을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @returns {$CancellablePromise<string[]>}
 */
export function GetDumpTableList(connID, database) {
    return $Call.ByID(58278011, connID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetExplain EXPLAIN 결과를 반환한다.
 * @param {string} connID
 * @param {string} sql
 * @returns {$CancellablePromise<schema$0.ExplainRow[]>}
 */
export function GetExplain(connID, sql) {
    return $Call.ByID(2692822278, connID, sql).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType16($result);
    }));
}

/**
 * GetExplainJSON EXPLAIN FORMAT=JSON 결과를 원시 JSON 문자열로 반환한다.
 * 트리/그래프 시각화 목적으로 사용한다.
 * @param {string} connID
 * @param {string} sql
 * @returns {$CancellablePromise<string>}
 */
export function GetExplainJSON(connID, sql) {
    return $Call.ByID(2986061408, connID, sql);
}

/**
 * GetForeignKeys 지정 데이터베이스의 모든 FK를 information_schema에서 조회한다.
 * ER 다이어그램 FK 엣지 생성에 사용한다.
 * @param {string} connID
 * @param {string} database
 * @returns {$CancellablePromise<schema$0.FKInfo[]>}
 */
export function GetForeignKeys(connID, database) {
    return $Call.ByID(2505029269, connID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType18($result);
    }));
}

/**
 * GetHistoryByDate 특정 날짜의 히스토리를 반환한다.
 * @param {string} date
 * @returns {$CancellablePromise<history$0.Entry[]>}
 */
export function GetHistoryByDate(date) {
    return $Call.ByID(1855652292, date).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetHistoryDates 히스토리가 있는 날짜 목록을 반환한다 (내림차순).
 * @returns {$CancellablePromise<string[]>}
 */
export function GetHistoryDates() {
    return $Call.ByID(631305114).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GetMCPAIPromptSnippet 사용자가 LLM 채팅창에 붙여넣을 영문 프롬프트를 생성한다.
 * BugFix-CY: MCP 가 이미 attach 됐다고 가정하지 않고, **서버 URL + Bearer 토큰을 직접 제시**해
 * AI 클라이언트가 Streamable HTTP MCP transport 로 자체 연결을 수립하도록 유도한다.
 * BugFix-CZ: 현재 MCP 설정(권한·포트·allowlist 정책) 및 실제로 노출되는 저장 연결 메타까지
 * 본문에 포함 → AI 가 첫 도구 호출 전에 환경을 알고 의도를 조율할 수 있다.
 * 
 * 의도적으로 영문 — Claude/Cursor 모두 영문 도구 description 과 일관되게 동작.
 * 서버가 실행 중이어야 유효한 endpoint 가 노출되므로 GetMCPClientConfigSnippet 과 동일한 가드를 둔다.
 * @returns {$CancellablePromise<string>}
 */
export function GetMCPAIPromptSnippet() {
    return $Call.ByID(2953167078);
}

/**
 * GetMCPClientConfigSnippet 클라이언트(Claude Code / Cursor) 용 JSON 설정 조각.
 * UI 의 "복사" 버튼이 이를 받아 사용자 클립보드에 넣는다.
 * @param {string} client
 * @returns {$CancellablePromise<string>}
 */
export function GetMCPClientConfigSnippet(client) {
    return $Call.ByID(4268809317, client);
}

/**
 * GetMCPConfig 현재 디스크에 저장된 MCP 설정을 반환한다 (토큰 제외).
 * @returns {$CancellablePromise<mcp$0.Config>}
 */
export function GetMCPConfig() {
    return $Call.ByID(144795951).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType21($result);
    }));
}

/**
 * GetMCPStatus 서버 상태 — UI 의 라이브 표시기에 쓰임.
 * @returns {$CancellablePromise<mcp$0.Status>}
 */
export function GetMCPStatus() {
    return $Call.ByID(4134259911).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType22($result);
    }));
}

/**
 * GetObjectDDL SP/Function/Trigger/Event 의 DDL을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} objType
 * @param {string} name
 * @returns {$CancellablePromise<string>}
 */
export function GetObjectDDL(connID, database, objType, name) {
    return $Call.ByID(2950537768, connID, database, objType, name);
}

/**
 * GetPerformanceInsights는 서버 성능 진단을 반환한다.
 * events_statements_summary_by_digest 는 서버 전역이라 database 인자는 없다.
 * @param {string} connID
 * @returns {$CancellablePromise<$models.PerformanceInsights | null>}
 */
export function GetPerformanceInsights(connID) {
    return $Call.ByID(4151238126, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType24($result);
    }));
}

/**
 * GetProcessList SHOW FULL PROCESSLIST를 반환한다.
 * @param {string} connID
 * @returns {$CancellablePromise<$models.ProcessRow[]>}
 */
export function GetProcessList(connID) {
    return $Call.ByID(156304516, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType26($result);
    }));
}

/**
 * GetProfile SHOW PROFILE 결과를 반환한다.
 * @param {string} connID
 * @returns {$CancellablePromise<schema$0.ProfileRow[]>}
 */
export function GetProfile(connID) {
    return $Call.ByID(169949408, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType28($result);
    }));
}

/**
 * GetQueryHistory 오늘 날짜 히스토리를 반환한다 (하위호환).
 * @returns {$CancellablePromise<history$0.Entry[]>}
 */
export function GetQueryHistory() {
    return $Call.ByID(4170271023).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * GetQueryTimeout 현재 쿼리 타임아웃(초)을 반환한다.
 * @returns {$CancellablePromise<number>}
 */
export function GetQueryTimeout() {
    return $Call.ByID(3077408696);
}

/**
 * GetResultLimit 현재 SELECT 결과 행 상한선을 반환한다.
 * @returns {$CancellablePromise<number>}
 */
export function GetResultLimit() {
    return $Call.ByID(1784546197);
}

/**
 * GetSavedConnections 저장된 연결 설정 목록을 반환한다 (비밀번호 제외).
 * 파일에는 이미 빈 값이어야 하지만, 혹시 마이그레이션 미수행이나 외부 편집으로
 * 평문이 남아있을 경우에도 프론트로 반출되지 않도록 방어적으로 비운다.
 * @returns {$CancellablePromise<connection$0.ConnectConfig[]>}
 */
export function GetSavedConnections() {
    return $Call.ByID(125394487).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType29($result);
    }));
}

/**
 * GetServerStatus SHOW [GLOBAL|SESSION] STATUS 반환.
 * @param {string} connID
 * @param {string} scope
 * @returns {$CancellablePromise<$models.VariableRow[]>}
 */
export function GetServerStatus(connID, scope) {
    return $Call.ByID(880383150, connID, scope).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * GetServerVariables SHOW [GLOBAL|SESSION] VARIABLES 반환.
 * @param {string} connID
 * @param {string} scope
 * @returns {$CancellablePromise<$models.VariableRow[]>}
 */
export function GetServerVariables(connID, scope) {
    return $Call.ByID(2767241245, connID, scope).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType31($result);
    }));
}

/**
 * GetSessionGroups 저장된 세션 그룹 목록을 반환한다.
 * @returns {$CancellablePromise<connection$0.SessionGroup[]>}
 */
export function GetSessionGroups() {
    return $Call.ByID(1207771097).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType33($result);
    }));
}

/**
 * GetTableDDL CREATE TABLE DDL을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<string>}
 */
export function GetTableDDL(connID, database, table) {
    return $Call.ByID(1199850583, connID, database, table);
}

/**
 * GetTableDefinition 테이블 전체 구조 (컬럼+인덱스+FK)를 반환한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<schema$0.TableDefinition | null>}
 */
export function GetTableDefinition(connID, database, table) {
    return $Call.ByID(3231045316, connID, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType35($result);
    }));
}

/**
 * GetTableMeta Phase 16 디자이너 전용 — 상단 탭/하단 그리드에 필요한 모든 메타를 한 번에 조회한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<schema$0.TableMeta | null>}
 */
export function GetTableMeta(connID, database, table) {
    return $Call.ByID(1010190892, connID, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType37($result);
    }));
}

/**
 * GetUserGrants 특정 사용자의 GRANT 목록을 반환한다.
 * @param {string} connID
 * @param {string} user
 * @param {string} host
 * @returns {$CancellablePromise<string[]>}
 */
export function GetUserGrants(connID, user, host) {
    return $Call.ByID(1773499651, connID, user, host).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * GrantPrivileges 사용자에게 권한을 부여한다.
 * @param {string} connID
 * @param {string} privileges
 * @param {string} onClause
 * @param {string} user
 * @param {string} host
 * @returns {$CancellablePromise<void>}
 */
export function GrantPrivileges(connID, privileges, onClause, user, host) {
    return $Call.ByID(395670205, connID, privileges, onClause, user, host);
}

/**
 * ImportCSVData CSV 문자열을 파싱하여 지정 테이블에 BATCH INSERT한다.
 * delimiter: 구분자 문자열 (예: ",", "\t", ";"). 빈 문자열이면 ","로 처리.
 * 반환: 삽입 결과 (inserted, skipped, errors)
 * @param {string} connID
 * @param {string} database
 * @param {string} table
 * @param {string} csvContent
 * @param {boolean} hasHeader
 * @param {string} delimiter
 * @returns {$CancellablePromise<query$0.ImportResult>}
 */
export function ImportCSVData(connID, database, table, csvContent, hasHeader, delimiter) {
    return $Call.ByID(633017308, connID, database, table, csvContent, hasHeader, delimiter).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType38($result);
    }));
}

/**
 * ImportConnections JSON 문자열에서 연결 설정을 가져온다.
 * v2 포맷(그룹 포함)과 v1 포맷(flat array) 모두 지원.
 * 기존 연결/그룹과 중복된 ID는 덮어쓴다.
 * @param {string} jsonStr
 * @returns {$CancellablePromise<number>}
 */
export function ImportConnections(jsonStr) {
    return $Call.ByID(1802682781, jsonStr);
}

/**
 * InsertRow 결과 그리드 — 신규 행을 INSERT한다.
 * columnValues에 포함된 컬럼만 INSERT하고 나머지는 DB 기본값으로 처리된다.
 * @param {string} connID
 * @param {string} database
 * @param {string} table
 * @param {query$0.ColumnValue[]} columnValues
 * @returns {$CancellablePromise<void>}
 */
export function InsertRow(connID, database, table, columnValues) {
    return $Call.ByID(3266618036, connID, database, table, columnValues);
}

/**
 * KillProcess KILL [CONNECTION|QUERY] <id>를 실행한다.
 * @param {string} connID
 * @param {number} processID
 * @param {boolean} killQuery
 * @returns {$CancellablePromise<void>}
 */
export function KillProcess(connID, processID, killQuery) {
    return $Call.ByID(3563357326, connID, processID, killQuery);
}

/**
 * ListColumns 컬럼 목록을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<schema$0.ColumnInfo[]>}
 */
export function ListColumns(connID, database, table) {
    return $Call.ByID(1374733344, connID, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType40($result);
    }));
}

/**
 * ListConnections 현재 활성 연결 목록을 반환한다.
 * @returns {$CancellablePromise<connection$0.ConnectionInfo[]>}
 */
export function ListConnections() {
    return $Call.ByID(786053378).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType42($result);
    }));
}

/**
 * ListDatabases 데이터베이스 목록을 반환한다.
 * @param {string} connID
 * @returns {$CancellablePromise<string[]>}
 */
export function ListDatabases(connID) {
    return $Call.ByID(4238628917, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * ListDatabasesFromConfig 연결 설정으로 임시 연결 후 DB 목록을 반환한다.
 * 연결 편집 모달에서 테스트 성공 후 DB 목록을 가져올 때 사용한다.
 * @param {connection$0.ConnectConfig} cfg
 * @returns {$CancellablePromise<string[]>}
 */
export function ListDatabasesFromConfig(cfg) {
    return $Call.ByID(2296282695, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType14($result);
    }));
}

/**
 * ListEvents 이벤트 목록을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @returns {$CancellablePromise<schema$0.ObjectInfo[]>}
 */
export function ListEvents(connID, database) {
    return $Call.ByID(172900752, connID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * ListFavorites 모든 즐겨찾기를 반환한다 (사용 횟수 내림차순).
 * @returns {$CancellablePromise<favorite$0.Snippet[]>}
 */
export function ListFavorites() {
    return $Call.ByID(3336245950).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType46($result);
    }));
}

/**
 * ListFunctions 함수 목록을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @returns {$CancellablePromise<schema$0.ObjectInfo[]>}
 */
export function ListFunctions(connID, database) {
    return $Call.ByID(2151539642, connID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * ListIndexes 인덱스 목록을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<schema$0.IndexInfo[]>}
 */
export function ListIndexes(connID, database, table) {
    return $Call.ByID(3383199879, connID, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType48($result);
    }));
}

/**
 * ListKnownHosts ~/.orcasql/known_hosts의 모든 항목을 반환한다.
 * @returns {$CancellablePromise<connection$0.KnownHostEntry[]>}
 */
export function ListKnownHosts() {
    return $Call.ByID(473219899).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType50($result);
    }));
}

/**
 * ListProcedures 저장 프로시저 목록을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @returns {$CancellablePromise<schema$0.ObjectInfo[]>}
 */
export function ListProcedures(connID, database) {
    return $Call.ByID(962989779, connID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * ListTables 테이블/뷰 목록을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @returns {$CancellablePromise<schema$0.TableInfo[]>}
 */
export function ListTables(connID, database) {
    return $Call.ByID(364749488, connID, database).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType52($result);
    }));
}

/**
 * ListTriggers 트리거 목록을 반환한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} table
 * @returns {$CancellablePromise<schema$0.ObjectInfo[]>}
 */
export function ListTriggers(connID, database, table) {
    return $Call.ByID(3347851412, connID, database, table).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType44($result);
    }));
}

/**
 * ListUsers mysql.user 테이블에서 사용자 목록을 반환한다.
 * @param {string} connID
 * @returns {$CancellablePromise<$models.UserRow[]>}
 */
export function ListUsers(connID) {
    return $Call.ByID(2023140511, connID).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType54($result);
    }));
}

/**
 * LoadSession 저장된 세션 상태를 반환한다.
 * @returns {$CancellablePromise<session$0.SessionState | null>}
 */
export function LoadSession() {
    return $Call.ByID(2280082259).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType56($result);
    }));
}

/**
 * OnStartup은 Wails v3 서비스 라이프사이클 훅이다.
 * @param {application$0.ServiceOptions} options
 * @returns {$CancellablePromise<void>}
 */
export function OnStartup(options) {
    return $Call.ByID(2232168041, options);
}

/**
 * OpenDevTools 현재 윈도우의 개발자 도구를 연다.
 * 도움말 메뉴 > 개발자 도구 진입점에서 호출된다.
 * production 빌드에서도 main.go 의 DevToolsEnabled=true 설정이 살아있는 한 동작한다.
 * @returns {$CancellablePromise<void>}
 */
export function OpenDevTools() {
    return $Call.ByID(4081882403);
}

/**
 * Ping 연결이 살아있는지 확인한다.
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function Ping(connID) {
    return $Call.ByID(1003072145, connID);
}

/**
 * PingWithLatency Ping을 수행하고 지연 시간(ms)을 반환한다.
 * StatusBar의 연결 상태 표시에 사용한다.
 * @param {string} connID
 * @returns {$CancellablePromise<number>}
 */
export function PingWithLatency(connID) {
    return $Call.ByID(3550877881, connID);
}

/**
 * Reconnect 기존 연결을 끊고 저장된 설정으로 재연결한다.
 * MySQL 8h wait_timeout 등으로 연결이 끊겼을 때 UI에서 호출한다.
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function Reconnect(connID) {
    return $Call.ByID(3863412110, connID);
}

/**
 * RecordHistoryEntry UI 측에서 직접 호출하는 행위(인라인 셀 수정·행 삽입 등
 * `ExecuteQuery` 를 거치지 않는 경로) 의 결과를 히스토리에 추가한다.
 * 
 * BugFix-CW: Messages·History 일관성 — 모든 쿼리 행위가 한곳에 기록되도록 한다.
 * 자동 채움 필드: 빈 ID 는 uuid.New, 0-time ExecutedAt 은 time.Now 로 대체.
 * 
 * Duration 은 nanoseconds(time.Duration 호환 정수). 프런트엔드는 ms 단위로
 * 측정한 값을 1_000_000 곱해 전달한다.
 * @param {history$0.Entry} entry
 * @returns {$CancellablePromise<void>}
 */
export function RecordHistoryEntry(entry) {
    return $Call.ByID(1923853384, entry);
}

/**
 * RegenerateMCPToken 토큰 강제 재발급 — 기존 클라이언트는 다음 호출 시 401.
 * 서버가 실행 중이면 자동 재시작하여 새 토큰을 적용.
 * @returns {$CancellablePromise<string>}
 */
export function RegenerateMCPToken() {
    return $Call.ByID(1152023458);
}

/**
 * RenameTable 테이블 이름을 변경한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} oldName
 * @param {string} newName
 * @returns {$CancellablePromise<void>}
 */
export function RenameTable(connID, database, oldName, newName) {
    return $Call.ByID(1939863997, connID, database, oldName, newName);
}

/**
 * ReorderGroups 그룹 전체 목록을 덮어쓰기하여 순서/부모 관계를 일괄 반영한다.
 * @param {connection$0.SessionGroup[]} groups
 * @returns {$CancellablePromise<void>}
 */
export function ReorderGroups(groups) {
    return $Call.ByID(2707744768, groups);
}

/**
 * ResetAllUserData 모든 사용자 데이터(연결·세션·히스토리·즐겨찾기·SSH known_hosts·로그·키체인 비밀번호)를
 * 영구 삭제하고 1.5초 뒤 앱을 종료한다.
 * 
 * 도움말 메뉴의 "모든 설정 초기화" 진입점에서 호출된다.
 * 동작:
 *  1. connections.json lock 시도 — 다른 인스턴스가 작업 중이면 차단
 *  2. 활성 연결 모두 Disconnect (TCP 핸들 해제)
 *  3. MCP 서버 중지 (이후 listener 가 더 이상 활성 connection 을 잡지 못하도록)
 *  4. connections.json 의 모든 connID 수집 → 키체인 3개 서비스 항목 Delete
 *  5. ~/.orcasql 디렉토리 통째로 RemoveAll
 *  6. MCP 토큰 키체인 항목 Delete (Phase 43)
 *  7. 1.5초 후 application Quit (프론트가 토스트 표시할 시간)
 * 
 * 부분 실패 시에도 가능한 만큼 정리하고 wrapped error 반환.
 * @returns {$CancellablePromise<void>}
 */
export function ResetAllUserData() {
    return $Call.ByID(1904216928);
}

/**
 * ResetSession 손상된 세션을 빈 상태로 초기화한다 (파일 + .bak 모두 제거).
 * Phase 14-D: 프론트엔드에서 LoadSession 실패 감지 시 호출.
 * @returns {$CancellablePromise<void>}
 */
export function ResetSession() {
    return $Call.ByID(2737204196);
}

/**
 * RevealMCPToken 평문 토큰을 1회 반환한다 — UI 의 "토큰 복사" 버튼에서만 호출.
 * 토큰이 아직 없으면 자동 발급.
 * @returns {$CancellablePromise<string>}
 */
export function RevealMCPToken() {
    return $Call.ByID(825324489);
}

/**
 * RevokePrivileges 사용자의 권한을 회수한다.
 * @param {string} connID
 * @param {string} privileges
 * @param {string} onClause
 * @param {string} user
 * @param {string} host
 * @returns {$CancellablePromise<void>}
 */
export function RevokePrivileges(connID, privileges, onClause, user, host) {
    return $Call.ByID(522895571, connID, privileges, onClause, user, host);
}

/**
 * SaveConnection 연결 설정을 로컬 파일 + 비밀번호는 OS 키체인에 저장한다.
 * MySQL / SSH / Proxy 세 가지 비밀번호 모두 키체인으로 분리되며, 파일에는 빈 문자열만 남는다.
 * 빈 비밀번호로 들어온 필드는 키체인을 덮어쓰지 않는다 — 편집 UX 상 사용자가 기존 값을 유지할 수 있게 하기 위함.
 * @param {connection$0.ConnectConfig} cfg
 * @returns {$CancellablePromise<void>}
 */
export function SaveConnection(cfg) {
    return $Call.ByID(865625064, cfg);
}

/**
 * SaveSession 현재 열린 탭 상태를 저장한다 (앱 종료 직전 호출).
 * @param {session$0.SessionState} state
 * @returns {$CancellablePromise<void>}
 */
export function SaveSession(state) {
    return $Call.ByID(1031450332, state);
}

/**
 * SaveSessionGroup 그룹을 생성 또는 수정한다.
 * @param {connection$0.SessionGroup} grp
 * @returns {$CancellablePromise<void>}
 */
export function SaveSessionGroup(grp) {
    return $Call.ByID(2152932687, grp);
}

/**
 * SearchHistory 쿼리 히스토리를 검색한다. date가 비어 있으면 전체 파일 검색.
 * @param {string} query
 * @param {string} date
 * @returns {$CancellablePromise<history$0.Entry[]>}
 */
export function SearchHistory(query, date) {
    return $Call.ByID(3950560707, query, date).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType20($result);
    }));
}

/**
 * SearchInDatabase 지정 데이터베이스의 모든 테이블/컬럼에서 키워드를 검색한다.
 * 결과가 많을 경우 테이블당 최대 maxPerTable 행으로 제한한다.
 * @param {string} connID
 * @param {string} database
 * @param {string} keyword
 * @param {number} maxPerTable
 * @returns {$CancellablePromise<$models.DataSearchResult[]>}
 */
export function SearchInDatabase(connID, database, keyword, maxPerTable) {
    return $Call.ByID(1696674927, connID, database, keyword, maxPerTable).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType58($result);
    }));
}

/**
 * SetAccountLock 계정 잠금 상태를 변경한다.
 * @param {string} connID
 * @param {string} user
 * @param {string} host
 * @param {boolean} lock
 * @returns {$CancellablePromise<void>}
 */
export function SetAccountLock(connID, user, host, lock) {
    return $Call.ByID(2051213161, connID, user, host, lock);
}

/**
 * SetQueryTimeout 쿼리 타임아웃을 변경한다. seconds는 5~300 범위.
 * @param {number} seconds
 * @returns {$CancellablePromise<void>}
 */
export function SetQueryTimeout(seconds) {
    return $Call.ByID(3887047172, seconds);
}

/**
 * SetResultLimit SELECT 결과 행 상한선을 변경한다. n은 100~1,000,000 범위.
 * @param {number} n
 * @returns {$CancellablePromise<void>}
 */
export function SetResultLimit(n) {
    return $Call.ByID(1871580017, n);
}

/**
 * SetVersion main.go에서 버전 문자열을 주입한다.
 * @param {string} v
 * @returns {$CancellablePromise<void>}
 */
export function SetVersion(v) {
    return $Call.ByID(194547285, v);
}

/**
 * StartMCPServer 수동 시작 — Config.Enabled=true 여야 함.
 * @returns {$CancellablePromise<void>}
 */
export function StartMCPServer() {
    return $Call.ByID(674663250);
}

/**
 * StopMCPServer 수동 중지 — graceful shutdown (5초 이내).
 * @returns {$CancellablePromise<void>}
 */
export function StopMCPServer() {
    return $Call.ByID(3658953848);
}

/**
 * SyncTableData 대상 DB에 생성된 동기화 SQL을 실행한다.
 * @param {string} dstConnID
 * @param {string} dstDB
 * @param {string} syncSQL
 * @returns {$CancellablePromise<void>}
 */
export function SyncTableData(dstConnID, dstDB, syncSQL) {
    return $Call.ByID(261249046, dstConnID, dstDB, syncSQL);
}

/**
 * TestConnection 저장하지 않고 연결 설정을 즉시 테스트한다.
 * 에러 종류(호스트 불가/인증 실패/DB 없음/SSH 오류)를 구분해 반환한다.
 * @param {connection$0.ConnectConfig} cfg
 * @returns {$CancellablePromise<$models.TestConnResult>}
 */
export function TestConnection(cfg) {
    return $Call.ByID(1257240193, cfg).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType59($result);
    }));
}

/**
 * TestMCPConnection 로컬 MCP 엔드포인트에 initialize 요청을 보내 응답을 검증한다.
 * 사용자가 환경설정에서 한 번 클릭해 활성화 직후 동작 여부를 빠르게 확인하는 용도.
 * 
 * 검증 항목 (모두 통과 시 Success=true):
 *   1. 서버가 running 상태
 *   2. 키체인 토큰으로 인증 통과
 *   3. Streamable HTTP transport 가 200 + 유효 JSON-RPC 응답 반환
 * @returns {$CancellablePromise<$models.TestMCPResult>}
 */
export function TestMCPConnection() {
    return $Call.ByID(3385043451).then(/** @type {($result: any) => any} */(($result) => {
        return $$createType60($result);
    }));
}

/**
 * UpdateConnectionLastUsed 연결의 마지막 사용 시각을 현재 시각으로 업데이트한다.
 * @param {string} connID
 * @returns {$CancellablePromise<void>}
 */
export function UpdateConnectionLastUsed(connID) {
    return $Call.ByID(2021593545, connID);
}

/**
 * UpdateFavorite 기존 즐겨찾기를 수정한다.
 * @param {favorite$0.Snippet} snippet
 * @returns {$CancellablePromise<void>}
 */
export function UpdateFavorite(snippet) {
    return $Call.ByID(723747856, snippet);
}

/**
 * UpdateMCPConfig 설정을 저장하고 필요 시 서버를 재시작한다.
 *   - Enabled false → 실행 중이면 Stop
 *   - Enabled true  → 재시작 (Stop → Start)
 * 
 * 포트나 권한 변경은 재시작을 통해 반영된다.
 * @param {mcp$0.Config} cfg
 * @returns {$CancellablePromise<void>}
 */
export function UpdateMCPConfig(cfg) {
    return $Call.ByID(180786590, cfg);
}

/**
 * UpdateRowValue 결과 그리드 인라인 편집 — 단일 셀 값을 UPDATE한다.
 * pkValues: WHERE 조건을 구성하는 PK 컬럼·값 쌍 배열
 * setNull: true이면 newValue를 무시하고 NULL로 설정
 * @param {string} connID
 * @param {string} database
 * @param {string} table
 * @param {string} column
 * @param {string} newValue
 * @param {boolean} setNull
 * @param {query$0.RowPKValue[]} pkValues
 * @returns {$CancellablePromise<void>}
 */
export function UpdateRowValue(connID, database, table, column, newValue, setNull, pkValues) {
    return $Call.ByID(2760936297, connID, database, table, column, newValue, setNull, pkValues);
}

/**
 * UseFavorite 즐겨찾기 사용 횟수를 증가시킨다.
 * @param {string} id
 * @returns {$CancellablePromise<void>}
 */
export function UseFavorite(id) {
    return $Call.ByID(1408498944, id);
}

// Private type creation functions
const $$createType0 = schema$0.AlterStatement.createFrom;
const $$createType1 = $Create.Nullable($$createType0);
const $$createType2 = sync$0.SchemaSyncResult.createFrom;
const $$createType3 = $Create.Nullable($$createType2);
const $$createType4 = sync$0.DataSyncResult.createFrom;
const $$createType5 = $Create.Nullable($$createType4);
const $$createType6 = query$0.MultiExecResult.createFrom;
const $$createType7 = $Create.Nullable($$createType6);
const $$createType8 = query$0.QueryResult.createFrom;
const $$createType9 = $Create.Nullable($$createType8);
const $$createType10 = $models.AppInfo.createFrom;
const $$createType11 = connection$0.ConnectConfig.createFrom;
const $$createType12 = $models.DatabaseOverview.createFrom;
const $$createType13 = $Create.Nullable($$createType12);
const $$createType14 = $Create.Array($Create.Any);
const $$createType15 = schema$0.ExplainRow.createFrom;
const $$createType16 = $Create.Array($$createType15);
const $$createType17 = schema$0.FKInfo.createFrom;
const $$createType18 = $Create.Array($$createType17);
const $$createType19 = history$0.Entry.createFrom;
const $$createType20 = $Create.Array($$createType19);
const $$createType21 = mcp$0.Config.createFrom;
const $$createType22 = mcp$0.Status.createFrom;
const $$createType23 = $models.PerformanceInsights.createFrom;
const $$createType24 = $Create.Nullable($$createType23);
const $$createType25 = $models.ProcessRow.createFrom;
const $$createType26 = $Create.Array($$createType25);
const $$createType27 = schema$0.ProfileRow.createFrom;
const $$createType28 = $Create.Array($$createType27);
const $$createType29 = $Create.Array($$createType11);
const $$createType30 = $models.VariableRow.createFrom;
const $$createType31 = $Create.Array($$createType30);
const $$createType32 = connection$0.SessionGroup.createFrom;
const $$createType33 = $Create.Array($$createType32);
const $$createType34 = schema$0.TableDefinition.createFrom;
const $$createType35 = $Create.Nullable($$createType34);
const $$createType36 = schema$0.TableMeta.createFrom;
const $$createType37 = $Create.Nullable($$createType36);
const $$createType38 = query$0.ImportResult.createFrom;
const $$createType39 = schema$0.ColumnInfo.createFrom;
const $$createType40 = $Create.Array($$createType39);
const $$createType41 = connection$0.ConnectionInfo.createFrom;
const $$createType42 = $Create.Array($$createType41);
const $$createType43 = schema$0.ObjectInfo.createFrom;
const $$createType44 = $Create.Array($$createType43);
const $$createType45 = favorite$0.Snippet.createFrom;
const $$createType46 = $Create.Array($$createType45);
const $$createType47 = schema$0.IndexInfo.createFrom;
const $$createType48 = $Create.Array($$createType47);
const $$createType49 = connection$0.KnownHostEntry.createFrom;
const $$createType50 = $Create.Array($$createType49);
const $$createType51 = schema$0.TableInfo.createFrom;
const $$createType52 = $Create.Array($$createType51);
const $$createType53 = $models.UserRow.createFrom;
const $$createType54 = $Create.Array($$createType53);
const $$createType55 = session$0.SessionState.createFrom;
const $$createType56 = $Create.Nullable($$createType55);
const $$createType57 = $models.DataSearchResult.createFrom;
const $$createType58 = $Create.Array($$createType57);
const $$createType59 = $models.TestConnResult.createFrom;
const $$createType60 = $models.TestMCPResult.createFrom;
