// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * AppInfo About 다이얼로그용 앱 정보.
 */
export class AppInfo {
    /**
     * Creates a new AppInfo instance.
     * @param {Partial<AppInfo>} [$$source = {}] - The source object to create the AppInfo.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("version" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["version"] = "";
        }
        if (!("description" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["description"] = "";
        }
        if (!("copyright" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["copyright"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new AppInfo instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {AppInfo}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new AppInfo(/** @type {Partial<AppInfo>} */($$parsedSource));
    }
}

/**
 * DataSearchResult 데이터 검색 결과 항목.
 */
export class DataSearchResult {
    /**
     * Creates a new DataSearchResult instance.
     * @param {Partial<DataSearchResult>} [$$source = {}] - The source object to create the DataSearchResult.
     */
    constructor($$source = {}) {
        if (!("table" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["table"] = "";
        }
        if (!("column" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["column"] = "";
        }
        if (!("rows" in $$source)) {
            /**
             * 매칭된 행 (문자열 변환)
             * @member
             * @type {string[][]}
             */
            this["rows"] = [];
        }
        if (!("total" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["total"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DataSearchResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DataSearchResult}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType1;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("rows" in $$parsedSource) {
            $$parsedSource["rows"] = $$createField2_0($$parsedSource["rows"]);
        }
        return new DataSearchResult(/** @type {Partial<DataSearchResult>} */($$parsedSource));
    }
}

/**
 * ProcessRow는 SHOW PROCESSLIST 한 행을 나타낸다.
 */
export class ProcessRow {
    /**
     * Creates a new ProcessRow instance.
     * @param {Partial<ProcessRow>} [$$source = {}] - The source object to create the ProcessRow.
     */
    constructor($$source = {}) {
        if (!("id" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["id"] = 0;
        }
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("db" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["db"] = "";
        }
        if (!("command" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["command"] = "";
        }
        if (!("time" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["time"] = 0;
        }
        if (!("state" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["state"] = "";
        }
        if (!("info" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["info"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new ProcessRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {ProcessRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new ProcessRow(/** @type {Partial<ProcessRow>} */($$parsedSource));
    }
}

/**
 * TestConnResult 연결 테스트 결과.
 * 에러 종류를 프론트엔드가 판단할 수 있도록 ErrorKind를 분리해 반환한다.
 */
export class TestConnResult {
    /**
     * Creates a new TestConnResult instance.
     * @param {Partial<TestConnResult>} [$$source = {}] - The source object to create the TestConnResult.
     */
    constructor($$source = {}) {
        if (!("ok" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["ok"] = false;
        }
        if (!("serverVer" in $$source)) {
            /**
             * 성공 시 MySQL 버전 문자열
             * @member
             * @type {string}
             */
            this["serverVer"] = "";
        }
        if (!("errorKind" in $$source)) {
            /**
             * "host" | "auth" | "database" | "ssh" | "proxy" | "tls" | "other"
             * @member
             * @type {string}
             */
            this["errorKind"] = "";
        }
        if (!("message" in $$source)) {
            /**
             * 원본 에러 메시지 (표시용)
             * @member
             * @type {string}
             */
            this["message"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestConnResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestConnResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestConnResult(/** @type {Partial<TestConnResult>} */($$parsedSource));
    }
}

/**
 * TestMCPResult 자가 헬스체크 결과 — 환경설정 패널의 "연결 테스트" 버튼이 받음.
 */
export class TestMCPResult {
    /**
     * Creates a new TestMCPResult instance.
     * @param {Partial<TestMCPResult>} [$$source = {}] - The source object to create the TestMCPResult.
     */
    constructor($$source = {}) {
        if (!("success" in $$source)) {
            /**
             * @member
             * @type {boolean}
             */
            this["success"] = false;
        }
        if (!("durationMs" in $$source)) {
            /**
             * @member
             * @type {number}
             */
            this["durationMs"] = 0;
        }
        if (/** @type {any} */(false)) {
            /**
             * @member
             * @type {string | undefined}
             */
            this["endpoint"] = undefined;
        }
        if (/** @type {any} */(false)) {
            /**
             * 실패 시 사용자에게 보여줄 짧은 문구
             * @member
             * @type {string | undefined}
             */
            this["message"] = undefined;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new TestMCPResult instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {TestMCPResult}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new TestMCPResult(/** @type {Partial<TestMCPResult>} */($$parsedSource));
    }
}

/**
 * UserRow는 MySQL 사용자 한 행.
 */
export class UserRow {
    /**
     * Creates a new UserRow instance.
     * @param {Partial<UserRow>} [$$source = {}] - The source object to create the UserRow.
     */
    constructor($$source = {}) {
        if (!("user" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["user"] = "";
        }
        if (!("host" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["host"] = "";
        }
        if (!("plugin" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["plugin"] = "";
        }
        if (!("passwordExpired" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["passwordExpired"] = "";
        }
        if (!("accountLocked" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["accountLocked"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new UserRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {UserRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new UserRow(/** @type {Partial<UserRow>} */($$parsedSource));
    }
}

/**
 * VariableRow는 SHOW VARIABLES / SHOW STATUS 한 행.
 */
export class VariableRow {
    /**
     * Creates a new VariableRow instance.
     * @param {Partial<VariableRow>} [$$source = {}] - The source object to create the VariableRow.
     */
    constructor($$source = {}) {
        if (!("name" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["name"] = "";
        }
        if (!("value" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["value"] = "";
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new VariableRow instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {VariableRow}
     */
    static createFrom($$source = {}) {
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        return new VariableRow(/** @type {Partial<VariableRow>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
const $$createType1 = $Create.Array($$createType0);
