// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

// eslint-disable-next-line @typescript-eslint/ban-ts-comment
// @ts-ignore: Unused imports
import { Create as $Create } from "@wailsio/runtime";

/**
 * DumpOptions SQL 덤프 옵션.
 */
export class DumpOptions {
    /**
     * Creates a new DumpOptions instance.
     * @param {Partial<DumpOptions>} [$$source = {}] - The source object to create the DumpOptions.
     */
    constructor($$source = {}) {
        if (!("connId" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["connId"] = "";
        }
        if (!("database" in $$source)) {
            /**
             * @member
             * @type {string}
             */
            this["database"] = "";
        }
        if (!("tables" in $$source)) {
            /**
             * 비어있으면 전체 테이블
             * @member
             * @type {string[]}
             */
            this["tables"] = [];
        }
        if (!("noData" in $$source)) {
            /**
             * 구조만 덤프 (DDL only)
             * @member
             * @type {boolean}
             */
            this["noData"] = false;
        }
        if (!("noCreate" in $$source)) {
            /**
             * 데이터만 덤프 (INSERT only)
             * @member
             * @type {boolean}
             */
            this["noCreate"] = false;
        }
        if (!("dropTable" in $$source)) {
            /**
             * DROP TABLE IF EXISTS 포함
             * @member
             * @type {boolean}
             */
            this["dropTable"] = false;
        }
        if (!("insertIgnore" in $$source)) {
            /**
             * INSERT IGNORE INTO 사용
             * @member
             * @type {boolean}
             */
            this["insertIgnore"] = false;
        }
        if (!("batchSize" in $$source)) {
            /**
             * INSERT 배치 크기 (기본 1000)
             * @member
             * @type {number}
             */
            this["batchSize"] = 0;
        }

        Object.assign(this, $$source);
    }

    /**
     * Creates a new DumpOptions instance from a string or object.
     * @param {any} [$$source = {}]
     * @returns {DumpOptions}
     */
    static createFrom($$source = {}) {
        const $$createField2_0 = $$createType0;
        let $$parsedSource = typeof $$source === 'string' ? JSON.parse($$source) : $$source;
        if ("tables" in $$parsedSource) {
            $$parsedSource["tables"] = $$createField2_0($$parsedSource["tables"]);
        }
        return new DumpOptions(/** @type {Partial<DumpOptions>} */($$parsedSource));
    }
}

// Private type creation functions
const $$createType0 = $Create.Array($Create.Any);
